# ~/.config/starship.toml

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[git_branch]
symbol = "ï˜ "

[git_status]
disabled=true

[nodejs]
symbol="ï¢˜ "
style="bold green"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "ğŸ„° ğŸ…† ğŸ…‚ îŒ½ "
[aws.region_aliases]
ap-northeast-2="Seoul"
