# ~/.config/starship.toml

[character]
success_symbol = "[>_](bold green)"

[battery]
full_symbol = "ï‰€ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
disabled=false

[[battery.display]]
threshold=99
charging_symbol="ï–ƒ "
style = "bold bright-green"

[[battery.display]]
threshold = 90
charging_symbol="ï–Š "
style = "bold green"

[[battery.display]]
threshold = 80
charging_symbol="ï–‰ "
style = "bold green"

[[battery.display]]
threshold = 60
charging_symbol="ï–ˆ "
style = "bold blue"

[[battery.display]]
threshold = 40
charging_symbol="ï–‡ "
style = "bold purple"

[[battery.display]]
threshold = 30
charging_symbol="ï–† "
style = "bold red"

[[battery.display]]
threshold = 20
charging_symbol="ï–… "
style = "bold red"


[git_branch]
symbol = "ï˜ "

[git_status]
disabled=true

[nodejs]
symbol="ï¢˜ "
style="bold green"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "ğŸ„° ğŸ…† ğŸ…‚ îŒ½ "
[aws.region_aliases]
ap-northeast-2="Seoul"
